// Bangla Translation Dictionary
export const bn = {
  "Image Studio": "ইমেজ স্টুডিও",
  "Video Studio": "ভিডিও স্টুডিও",
  "Lip Sync": "লিপ সিঙ্ক",
  "Cinema": "সিনেমা",
  "Settings": "সেটিংস",
  "Generate": "জেনারেট করুন",
  "Generating": "জেনারেট হচ্ছে...",
  "Download": "ডাউনলোড",
  "History": "ইতিহাস",
  "Clear": "মুছুন",
  "Cancel": "বাতিল",
  "Save": "সেভ করুন",
  "Close": "বন্ধ করুন",
  "Loading": "লোড হচ্ছে...",
  "Error": "ত্রুটি",
  "Success": "সফল",
  "Describe the image you want to create": "আপনি যে ছবি তৈরি করতে চান তার বর্ণনা দিন",
  "Describe how to transform this image": "এই ছবিটি কীভাবে পরিবর্তন করতে চান তার বর্ণনা দিন",
  "Reference image": "রেফারেন্স ইমেজ",
  "Add images": "ছবি যোগ করুন",
  "Aspect Ratio": "অ্যাসপেক্ট রেশিও",
  "Quality": "কোয়ালিটি",
  "Model": "মডেল",
  "Available models": "উপলব্ধ মডেলগুলো",
  "Search models": "মডেল খুঁজুন",
  "Describe the video you want to create": "আপনি যে ভিডিও তৈরি করতে চান তার বর্ণনা দিন",
  "Describe how to animate this image": "এই ছবিটি কীভাবে অ্যানিমেট করতে চান তার বর্ণনা দিন",
  "Duration": "সময়কাল",
  "seconds": "সেকেন্ড",
  "Portrait Image": "পোর্ট্রেইট ছবি",
  "Video": "ভিডিও",
  "Audio": "অডিও",
  "Upload portrait": "পোর্ট্রেইট আপলোড করুন",
  "Upload video": "ভিডিও আপলোড করুন",
  "Upload audio": "অডিও আপলোড করুন",
  "Animate portraits or sync lips to audio with AI": "AI দিয়ে পোর্ট্রেইট অ্যানিমেট করুন অথবা অডিওতে ঠোঁট সিঙ্ক করুন",
  "Camera": "ক্যামেরা",
  "Lens": "লেন্স",
  "Focal Length": "ফোকাল লেন্থ",
  "Aperture": "অ্যাপারচার",
  "What would you shoot with infinite budget?": "অসীম বাজেটে আপনি কী শুট করতেন?",
  "Camera Configuration": "ক্যামেরা কনফিগারেশন",
  "Select hardware & optics": "হার্ডওয়্যার এবং অপটিক্স নির্বাচন করুন",
  "API Key": "এপিআই কি",
  "Enter your API key": "আপনার এপিআই কি দিন",
  "Active API Key": "সক্রিয় এপিআই কি",
  "Change API Key": "এপিআই কি পরিবর্তন করুন",
  "Authentication": "প্রমাণীকরণ",
  "Upload files": "ফাইল আপলোড করুন",
  "Upload History": "আপলোড ইতিহাস",
  "Use Selected": "নির্বাচিত ব্যবহার করুন",
  "selected": "নির্বাচিত",
  "of": "এর",
  "images": "ছবি",
  "Please enter a prompt": "অনুগ্রহ করে একটি প্রম্পট লিখুন",
  "Please upload a reference image": "অনুগ্রহ করে একটি রেফারেন্স ছবি আপলোড করুন",
  "Generation failed": "জেনারেশন ব্যর্থ হয়েছে",
  "No image URL returned": "কোনো ছবির URL ফেরত আসেনি",
  "Open Generative AI": "ওপেন জেনারেটিভ এআই",
  "Bangla AI Studio": "বাংলা এআই স্টুডিও",
  "Uncensored AI Image & Video Generation": "অনসেন্সড এআই ইমেজ এবং ভিডিও জেনারেশন",
  "Free, open-source, unrestricted": "বিনামূল্যে, ওপেন-সোর্স, বিনা বিধি-নিষেধ",
};

// Translation helper
export function t(key) {
  return bn[key] || key;
}
